### ISSUE TITLE
Failed to initialize add-in 

### ISSUE THREAD

**Issue by Lazarica-t** [johnpierson/WhatTheDyn#4]
Hi, I'm getting an error after install. It seams it doesn't find **WhatTheDynamo.dll**, but when I checked the addin folder I can see it's there... so I'm not sure what's going one here 😕 

![image](https://github.com/johnpierson/WhatTheDyn/assets/49474519/cb68c6c0-fac9-414d-88a2-3585866bd6a5)

A workaround that worked for me was to copy **WhatTheDynamo.dll** directly in the Revit install folder, but I don't think this is how things are intended to work 😄

**Comment by johnpierson** [comment]
Can you show me the .addin file contents?

**Comment by Lazarica-t** [comment]
I have no other add-ons installed.. just this one

![image](https://github.com/johnpierson/WhatTheDyn/assets/49474519/cc4d4812-aa82-4372-881c-0e9d19c9b8d1)

**Comment by johnpierson** [comment]
edit the .addin file in a text editor

**Comment by Lazarica-t** [comment]
Did you mean this ? 😄 

![image](https://github.com/johnpierson/WhatTheDyn/assets/49474519/46998bbe-0433-48d4-b3bc-28e985e4cf28)

**Comment by johnpierson** [comment]
Replace it with this one. I will update the installer too.

https://github.com/johnpierson/WhatTheDyn/blob/main/_release/WhatTheDynamo.addin

**Comment by Lazarica-t** [comment]
It worked! Cheers! 🥳

**Comment by johnpierson** [comment]
And fixed in the installer here now: https://johntpierson.gumroad.com/l/whatTheDyn
